environment                  = "testing"
cluster_name                 =  "ekstest"
vpc_cidr                     =  "192.168.0.0/16"
vpc_name                     =  "main"
public_subnets_cidr          =  ["192.168.0.0/24", "192.168.1.0/24"]
private_subnets_cidr         =  ["192.168.4.0/24", "192.168.5.0/24"]
availability_zones_public    =  ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
availability_zones_private   =  ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
cidr_block-internet_gw       =  "0.0.0.0/0"
cidr_block-nat_gw            =  "0.0.0.0/0"
eks_node_group_instance_types=  "t2.micro"
fargate_namespace            =  "fargate-node"
secret_id                    =  "database"
identifier                   =  "database"
allocated_storage            =  20
storage_type                 =  "gp2"
engine                       =  "mysql"
engine_version               =  5.7
instance_class               =  "db.t2.micro"
database_name                =  "db"
kubernetes_version           = "1.21"
